
name: CI Nick poke workflow
on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@main  # склонируем репозиторий GitHub main ветки в рабочее пространство вашего workflow
      - uses: actions/setup-python@v3 # установка питона
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Check pwd
        run: pwd
      - name: Check ls root/poke_api
        run: ls -la poke_api/
      - name: Install requirements.txt
        run: pip install -r poke_api/requirements.txt
      - name: Tests
        run: python poke_api/manage.py test
  db:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:13.0-alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env:
      # Учетные данные, которые можно будет переопределить
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1000g0001
      - POSTGRES_DB=poke_api
  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      # определим переменньіе с гита secrets что бьі потом испоьзовать их в run:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME_IMAGE }}
    steps:
      - name: Login to docker
        # --password-stdin необходим для автоматизации процесса аутентификации в Docker-репозитории в средах,
        # где нет возможности вводить пароль вручную, например, в CI/CD платформах.
        # run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin
      - uses: actions/checkout@main
      - name: Check pwd
        run: pwd
      - name: Check ls root
        run: ls -la
      - name: Build image
        # Переменная ${GITHUB_REF} является переменной окружения, которая хранит имя текущей ветки в вашем репозитории GitHub.
        # Например, если текущая ветка - refs/heads/main, то ${GITHUB_REF:11} вернет main.
        # . (точка) используется для указания текущей директории.
        # ./ (точка с наклонной линией)означает текущую директорию, где находится Dockerfile.
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
        # run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f poke_api/Dockerfile .
      - name: Push image to docker
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}


volumes:
  postgres_volume:



